# Generated by Django 5.2.7 on 2025-10-25 16:58

import django.core.validators
import languages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='languageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languageCode', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', message='This field can only contain alphabetic characters.'), languages.models.validate_no_numbers])),
                ('languages', models.CharField(max_length=25, unique=True, validators=[languages.models.validate_no_numbers])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
